%Diccionario
determinante --> [el].
determinante --> [la].
determinante --> [un].
determinante --> [una].
nombre --> [hombre].
nombre --> [mujer].
nombre --> [juan].
nombre --> [mar�a].
nombre --> [manzanas].
nombre --> [manzana].
nombre --> [gato].
nombre --> [rat�n].
nombre --> [alumno].
nombre --> [ratones].
nombre --> [universidad].
verbo --> [ama].
verbo --> [come].
verbo --> [estudia].
verbo --> [era].
verbo --> [caz�].
adjetivo --> [roja].
adjetivo --> [negro].
adjetivo --> [grande].
adjetivo --> [gris].
adjetivo --> [peque�o].
preposicion --> [en].
preposicion --> [a].
pronombre --> [que].
